image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
variables:
  TF_ROOT: ${CI_PROJECT_DIR}
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_PROJECT_NAME}

before_script:
  - cd ${TF_ROOT}

stages:
  - validate
  - release

validate:
  stage: validate
  script:
    - echo "Using version:"
    - gitlab-terraform -version
    - gitlab-terraform init
    - gitlab-terraform validate

release:
  image: node:dubnium
  stage: release
  script:
    - add git git-core
    - npm i semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/gitlab @semantic-release/git @semantic-release/npm @semantic-release/release-notes-generator semantic-release-slack-bot
    - npx semantic-release
  only:
    - main
  except:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TITLE =~ /^RELEASE:.+$/