branches:
  - name: 'main'
    prerelease: false
ci: true
debug: true
dryRun: false
tagFormat: 'v${version}'

# Global plugin options
preset: 'conventionalcommits'
githubUrl: 'https://api.github.com/'

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator':
      groupBy: 'type'
      commitGroupsSort: 'title'
      commitsSort: 'header'
      linkCompare: true
      linkReferences: true
  - '@semantic-release/changelog':
      changelogFile: 'CHANGELOG.md'
  - '@semantic-release/git':
      message: 'RELEASE: ${nextRelease.version}'
      assets:
        - 'CHANGELOG.md'
        - 'package.json'
  - '@semantic-release/github'
  - path: 'semantic-release-slack-bot'
    successComment: true
    failTitle: 'Semantic Release Failed'
    notifyOnSuccess: true
    notifyOnFail: true